version: "3"
services: 
  mysql_cursos:
    container_name: mysql_cursos
    hostname: mysql_cursos
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes: 
      - D:\docker-volumes\mysqlonly\mysql_cursos:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base_de_dados
      MYSQL_PASSWORD: root
      TZ: America/Sao_Paulo